In [1]:
import pandas as pd
import numpy as np
from itertools import product

In [2]:
brs_ab_seq = [[0,0], [0,1], [1,0], [1,1]]
brs_cd_seq = [[0,1], [1,0], [1,1], [0,0]]
brs_ef_seq = brs_cd_seq
brs_product = [brs_ef_seq, brs_ab_seq, brs_cd_seq]

In [3]:
abcdefs = []
for ef, ab, cd in product(*brs_product):
    abcdef = ab + cd + ef
    abcdefs.append(abcdef)
    
df = pd.DataFrame(abcdefs, columns=["a","b","c","d","e","f"])
df

a  b  c  d  e  f
0   0  0  0  1  0  1
1   0  0  1  0  0  1
2   0  0  1  1  0  1
3   0  0  0  0  0  1
4   0  1  0  1  0  1
.. .. .. .. .. .. ..
59  1  0  0  0  0  0
60  1  1  0  1  0  0
61  1  1  1  0  0  0
62  1  1  1  1  0  0
63  1  1  0  0  0  0

[64 rows x 6 columns]

In [4]:
j_to_i = {
    3:13,
    6:1,
    7:9,
    11:11,
    14:3,
    15:14,
    17:15,
    19:16,
    21:17,
    23:12,
    25:5,
    27:10,
    29:7,
    31:18,
    33:19,
    37:20,
    38:4,
    41:8,
    45:6,
    46:2,
}
assert len(j_to_i) == 20
assert len(set(j_to_i.keys())) == 20
assert len(set(j_to_i.values())) == 20

df["j"] = list(range(1, 65))
df["i"] = df.j.map(j_to_i)

brs_attacks = ["a","b","c","a","a","d","e","a","f","b","e","b","f","d","c","f","c","a","c","a","c","b","e","b","e","a","e","a","e","b","c","b","c","b","g","b","c","d","g","g","e","b","g","b","e","d","g","g","a","a","g","a","a","b","g","a","f","a","g","a","f","b","g","b"]
df["brs_attack"] = brs_attacks

pgv_attacks = ["-","B","B","-","D","-","D","-","B","B","F","F","-","-","D","-","-","B","B","-","$\checkmark$","D","$\checkmark$","D","FP","FP","B","B","-","D","B","-","P","FP","FP","P","D","-","D","-","FP","FP","B","B","D","-","D","-","P","FP","FP","P","$\checkmark$","D","$\checkmark$","D","B","B","F","F","P","D","F","D"]
ordered = []
for i in range(4):
    ordered += pgv_attacks[i::4]

df["pgv_attack"] = ordered

assert sum(df["pgv_attack"] == "-") == 15
assert sum(df["pgv_attack"] == "D") == 14
assert sum(df["pgv_attack"] == "P") == 5
assert sum(df["pgv_attack"] == "B") == 13
assert sum(df["pgv_attack"] == "F") == 5
assert sum(df["pgv_attack"] == "FP") == 8
assert sum(df["pgv_attack"] == "$\checkmark$") == 4

pd.set_option('display.max_rows', None)
df

a  b  c  d  e  f   j     i brs_attack    pgv_attack
0   0  0  0  1  0  1   1   NaN          a             -
1   0  0  1  0  0  1   2   NaN          b             D
2   0  0  1  1  0  1   3  13.0          c             B
3   0  0  0  0  0  1   4   NaN          a             -
4   0  1  0  1  0  1   5   NaN          a             -
5   0  1  1  0  0  1   6   1.0          d  $\checkmark$
6   0  1  1  1  0  1   7   9.0          e            FP
7   0  1  0  0  0  1   8   NaN          a             -
8   1  0  0  1  0  1   9   NaN          f             P
9   1  0  1  0  0  1  10   NaN          b             D
10  1  0  1  1  0  1  11  11.0          e            FP
11  1  0  0  0  0  1  12   NaN          b             D
12  1  1  0  1  0  1  13   NaN          f             P
13  1  1  1  0  0  1  14   3.0          d  $\checkmark$
14  1  1  1  1  0  1  15  14.0          c             B
15  1  1  0  0  0  1  16   NaN          f             P
16  0  0  0  1  1  0  17  15.0          c             B
17  0  0  1  0  1  0  18   NaN          a             -
18  0  0  1  1  1  0  19  16.0          c             B
19  0  0  0  0  1  0  20   NaN          a             -
20  0  1  0  1  1  0  21  17.0          c             B
21  0  1  1  0  1  0  22   NaN          b             D
22  0  1  1  1  1  0  23  12.0          e            FP
23  0  1  0  0  1  0  24   NaN          b             D
24  1  0  0  1  1  0  25   5.0          e            FP
25  1  0  1  0  1  0  26   NaN          a             -
26  1  0  1  1  1  0  27  10.0          e            FP
27  1  0  0  0  1  0  28   NaN          a             -
28  1  1  0  1  1  0  29   7.0          e            FP
29  1  1  1  0  1  0  30   NaN          b             D
30  1  1  1  1  1  0  31  18.0          c             B
31  1  1  0  0  1  0  32   NaN          b             D
32  0  0  0  1  1  1  33  19.0          c             B
33  0  0  1  0  1  1  34   NaN          b             D
34  0  0  1  1  1  1  35   NaN          g             F
35  0  0  0  0  1  1  36   NaN          b             D
36  0  1  0  1  1  1  37  20.0          c             B
37  0  1  1  0  1  1  38   4.0          d  $\checkmark$
38  0  1  1  1  1  1  39   NaN          g             B
39  0  1  0  0  1  1  40   NaN          g             B
40  1  0  0  1  1  1  41   8.0          e            FP
41  1  0  1  0  1  1  42   NaN          b             D
42  1  0  1  1  1  1  43   NaN          g             B
43  1  0  0  0  1  1  44   NaN          b             D
44  1  1  0  1  1  1  45   6.0          e            FP
45  1  1  1  0  1  1  46   2.0          d  $\checkmark$
46  1  1  1  1  1  1  47   NaN          g             F
47  1  1  0  0  1  1  48   NaN          g             F
48  0  0  0  1  0  0  49   NaN          a             -
49  0  0  1  0  0  0  50   NaN          a             -
50  0  0  1  1  0  0  51   NaN          g             F
51  0  0  0  0  0  0  52   NaN          a             -
52  0  1  0  1  0  0  53   NaN          a             -
53  0  1  1  0  0  0  54   NaN          b             D
54  0  1  1  1  0  0  55   NaN          g             B
55  0  1  0  0  0  0  56   NaN          a             -
56  1  0  0  1  0  0  57   NaN          f             P
57  1  0  1  0  0  0  58   NaN          a             -
58  1  0  1  1  0  0  59   NaN          g             B
59  1  0  0  0  0  0  60   NaN          a             -
60  1  1  0  1  0  0  61   NaN          f             P
61  1  1  1  0  0  0  62   NaN          b             D
62  1  1  1  1  0  0  63   NaN          g             F
63  1  1  0  0  0  0  64   NaN          b             D

In [5]:
def row_to_okx(row):
    a,b,c,d,e,f = row.a,row.b,row.c,row.d,row.e,row.f
    o = (a,b)
    k = (c,d)
    x = (e,f)
    return o,k,x

def row_to_okxy3(row):
    a,b,c,d,e,f = row.a,row.b,row.c,row.d,row.e,row.f
    o = np.array([a,b,1])
    k = np.array([c,d,0])
    x = np.array([e,f,0])
    y = np.array([0,0,1])
    return o,k,x,y

from numpy.linalg import matrix_rank

def linicrypt_secure(row):
    o,k,x = row_to_okx(row)
    non_zero = o != (0,0) and k != (0,0) and x!= (0,0)
    return non_zero and o != k and k != x

def linicrypt_degenerate(row):
    o,k,x,y = row_to_okxy3(row)
    rank = matrix_rank([o,k,x,y])
    print(o,k,x,y)
    print(rank)
    return rank < 3

def linicrypt_det_solv_fix_o_k_f(row):
    if linicrypt_degenerate(row):
        return False
    x_in_span = matrix_rank([o,k,x]) == matrix_rank([o,k])
    y_not_in_span = matrix_rank([o,k,x]) < matrix_rank([o,k,x,y])
    return x_in_span and y_not_in_span

def linicrypt_det_solv_fix_o_k_b(row):
    if linicrypt_degenerate(row):
        return False
    y_in_span = matrix_rank([o,k,y]) == matrix_rank([o,k])
    x_not_in_span = matrix_rank([o,k,y]) < matrix_rank([o,k,y,x])
    return y_in_span and x_not_in_span

def is_in_span(Q: list[np.array], F:list[np.array]):
    return matrix_rank(Q + F) == matrix_rank(F)

def det_solv_fix(C: (np.array, np.array, np.array), Fix: list[np.array]):
    k, x, y = C
    Q = [k,x]
    a = [y]
    forward = is_in_span(Q, Fix) and not is_in_span(a, Fix)
    Q = [k,y]
    a = [x]
    backward = is_in_span(Q, Fix) and not is_in_span(a, Fix)
    return forward or backward

def linicrypt_det_solv_fix_o_h(row):
    o,k,x,y = row_to_okxy3(row)
    C = (k,x,y)
    h = np.array([1,0,0])
    return det_solv_fix(C, [o, h])

def linicrypt_permutation(row):
    o,k,x,y = row_to_okxy3(row)
    m = np.array([0,1,0])
    return is_in_span([k,x], [m])

def all_linicrypt_attacks(row):
    attacks = []
    if linicrypt_secure(row):
        attacks += ["Secure by MD Paradigm"]
    if linicrypt_det_solv_fix_o_h(row):
        attacks += ["Det. solv. fix. <o,h>"]
    if linicrypt_degenerate(row):
        attacks += ["Degenerate"]
    if linicrypt_permutation(row):
        attacks += ["Permutation attack"]
    return tuple(attacks)

def linicrypt_attack(row):
    attacks = []
    if linicrypt_secure(row):
        return "Secure"
    elif linicrypt_degenerate(row):
        return "Degenerate"
    elif linicrypt_det_solv_fix_o_h(row):
        return "$\<\O, \\vh\>$-Collision Structure"
    elif linicrypt_permutation(row):
        return "Permutation attack"
    return "TBD"

def linicrypt_attack_num(row):
    attacks = []
    if linicrypt_secure(row):
        return 3
    elif linicrypt_degenerate(row):
        return 0
    elif linicrypt_det_solv_fix_o_h(row):
        return 1
    elif linicrypt_permutation(row):
        return 2
    return 4
    
    
df["linicrypt_attack"] = df.apply(linicrypt_attack, axis=1)
df["linicrypt_num"] = df.apply(linicrypt_attack_num, axis=1)
df["linicrypt_all_attacks"] = df.apply(all_linicrypt_attacks, axis=1)
df

[0 0 1] [0 1 0] [0 1 0] [0 0 1]
2
[0 0 1] [1 0 0] [0 1 0] [0 0 1]
3
[0 0 1] [1 1 0] [0 1 0] [0 0 1]
3
[0 0 1] [0 0 0] [0 1 0] [0 0 1]
2
[0 1 1] [0 1 0] [0 1 0] [0 0 1]
2
[0 1 1] [0 0 0] [0 1 0] [0 0 1]
2
[1 0 1] [0 1 0] [0 1 0] [0 0 1]
3
[1 0 1] [1 0 0] [0 1 0] [0 0 1]
3
[1 0 1] [0 0 0] [0 1 0] [0 0 1]
3
[1 1 1] [0 1 0] [0 1 0] [0 0 1]
3
[1 1 1] [1 1 0] [0 1 0] [0 0 1]
3
[1 1 1] [0 0 0] [0 1 0] [0 0 1]
3
[0 0 1] [0 1 0] [1 0 0] [0 0 1]
3
[0 0 1] [1 0 0] [1 0 0] [0 0 1]
2
[0 0 1] [1 1 0] [1 0 0] [0 0 1]
3
[0 0 1] [0 0 0] [1 0 0] [0 0 1]
2
[0 1 1] [0 1 0] [1 0 0] [0 0 1]
3
[0 1 1] [1 0 0] [1 0 0] [0 0 1]
3
[0 1 1] [0 0 0] [1 0 0] [0 0 1]
3
[1 0 1] [1 0 0] [1 0 0] [0 0 1]
2
[1 0 1] [0 0 0] [1 0 0] [0 0 1]
2
[1 1 1] [1 0 0] [1 0 0] [0 0 1]
3
[1 1 1] [1 1 0] [1 0 0] [0 0 1]
3
[1 1 1] [0 0 0] [1 0 0] [0 0 1]
3
[0 0 1] [0 1 0] [1 1 0] [0 0 1]
3
[0 0 1] [1 0 0] [1 1 0] [0 0 1]
3
[0 0 1] [1 1 0] [1 1 0] [0 0 1]
2
[0 0 1] [0 0 0] [1 1 0] [0 0 1]
2
[0 1 1] [0 1 0] [1 1 0] [0 0 1]
3
[0 1 1] [1 1 0

a  b  c  d  e  f   j     i brs_attack    pgv_attack  \
0   0  0  0  1  0  1   1   NaN          a             -   
1   0  0  1  0  0  1   2   NaN          b             D   
2   0  0  1  1  0  1   3  13.0          c             B   
3   0  0  0  0  0  1   4   NaN          a             -   
4   0  1  0  1  0  1   5   NaN          a             -   
5   0  1  1  0  0  1   6   1.0          d  $\checkmark$   
6   0  1  1  1  0  1   7   9.0          e            FP   
7   0  1  0  0  0  1   8   NaN          a             -   
8   1  0  0  1  0  1   9   NaN          f             P   
9   1  0  1  0  0  1  10   NaN          b             D   
10  1  0  1  1  0  1  11  11.0          e            FP   
11  1  0  0  0  0  1  12   NaN          b             D   
12  1  1  0  1  0  1  13   NaN          f             P   
13  1  1  1  0  0  1  14   3.0          d  $\checkmark$   
14  1  1  1  1  0  1  15  14.0          c             B   
15  1  1  0  0  0  1  16   NaN          f             P   
16  0  0  0  1  1  0  17  15.0          c             B   
17  0  0  1  0  1  0  18   NaN          a             -   
18  0  0  1  1  1  0  19  16.0          c             B   
19  0  0  0  0  1  0  20   NaN          a             -   
20  0  1  0  1  1  0  21  17.0          c             B   
21  0  1  1  0  1  0  22   NaN          b             D   
22  0  1  1  1  1  0  23  12.0          e            FP   
23  0  1  0  0  1  0  24   NaN          b             D   
24  1  0  0  1  1  0  25   5.0          e            FP   
25  1  0  1  0  1  0  26   NaN          a             -   
26  1  0  1  1  1  0  27  10.0          e            FP   
27  1  0  0  0  1  0  28   NaN          a             -   
28  1  1  0  1  1  0  29   7.0          e            FP   
29  1  1  1  0  1  0  30   NaN          b             D   
30  1  1  1  1  1  0  31  18.0          c             B   
31  1  1  0  0  1  0  32   NaN          b             D   
32  0  0  0  1  1  1  33  19.0          c             B   
33  0  0  1  0  1  1  34   NaN          b             D   
34  0  0  1  1  1  1  35   NaN          g             F   
35  0  0  0  0  1  1  36   NaN          b             D   
36  0  1  0  1  1  1  37  20.0          c             B   
37  0  1  1  0  1  1  38   4.0          d  $\checkmark$   
38  0  1  1  1  1  1  39   NaN          g             B   
39  0  1  0  0  1  1  40   NaN          g             B   
40  1  0  0  1  1  1  41   8.0          e            FP   
41  1  0  1  0  1  1  42   NaN          b             D   
42  1  0  1  1  1  1  43   NaN          g             B   
43  1  0  0  0  1  1  44   NaN          b             D   
44  1  1  0  1  1  1  45   6.0          e            FP   
45  1  1  1  0  1  1  46   2.0          d  $\checkmark$   
46  1  1  1  1  1  1  47   NaN          g             F   
47  1  1  0  0  1  1  48   NaN          g             F   
48  0  0  0  1  0  0  49   NaN          a             -   
49  0  0  1  0  0  0  50   NaN          a             -   
50  0  0  1  1  0  0  51   NaN          g             F   
51  0  0  0  0  0  0  52   NaN          a             -   
52  0  1  0  1  0  0  53   NaN          a             -   
53  0  1  1  0  0  0  54   NaN          b             D   
54  0  1  1  1  0  0  55   NaN          g             B   
55  0  1  0  0  0  0  56   NaN          a             -   
56  1  0  0  1  0  0  57   NaN          f             P   
57  1  0  1  0  0  0  58   NaN          a             -   
58  1  0  1  1  0  0  59   NaN          g             B   
59  1  0  0  0  0  0  60   NaN          a             -   
60  1  1  0  1  0  0  61   NaN          f             P   
61  1  1  1  0  0  0  62   NaN          b             D   
62  1  1  1  1  0  0  63   NaN          g             F   
63  1  1  0  0  0  0  64   NaN          b             D   

                     linicrypt_attack  linicrypt_num  \
0                          Degenerate              0   
1   $\<\O, \vh\>$-Collision Structure              1   


In [6]:
for brs_attack, group in df.groupby(["pgv_attack", "brs_attack", "linicrypt_attack"]):
    display(group)

a  b  c  d  e  f   j    i brs_attack    pgv_attack linicrypt_attack  \
5   0  1  1  0  0  1   6  1.0          d  $\checkmark$           Secure   
13  1  1  1  0  0  1  14  3.0          d  $\checkmark$           Secure   
37  0  1  1  0  1  1  38  4.0          d  $\checkmark$           Secure   
45  1  1  1  0  1  1  46  2.0          d  $\checkmark$           Secure   

    linicrypt_num     linicrypt_all_attacks  
5               3  (Secure by MD Paradigm,)  
13              3  (Secure by MD Paradigm,)  
37              3  (Secure by MD Paradigm,)  
45              3  (Secure by MD Paradigm,)

a  b  c  d  e  f   j   i brs_attack pgv_attack linicrypt_attack  \
0   0  0  0  1  0  1   1 NaN          a          -       Degenerate   
3   0  0  0  0  0  1   4 NaN          a          -       Degenerate   
4   0  1  0  1  0  1   5 NaN          a          -       Degenerate   
7   0  1  0  0  0  1   8 NaN          a          -       Degenerate   
17  0  0  1  0  1  0  18 NaN          a          -       Degenerate   
19  0  0  0  0  1  0  20 NaN          a          -       Degenerate   
25  1  0  1  0  1  0  26 NaN          a          -       Degenerate   
27  1  0  0  0  1  0  28 NaN          a          -       Degenerate   
48  0  0  0  1  0  0  49 NaN          a          -       Degenerate   
49  0  0  1  0  0  0  50 NaN          a          -       Degenerate   
51  0  0  0  0  0  0  52 NaN          a          -       Degenerate   
52  0  1  0  1  0  0  53 NaN          a          -       Degenerate   
55  0  1  0  0  0  0  56 NaN          a          -       Degenerate   
57  1  0  1  0  0  0  58 NaN          a          -       Degenerate   
59  1  0  0  0  0  0  60 NaN          a          -       Degenerate   

    linicrypt_num                              linicrypt_all_attacks  
0               0                   (Degenerate, Permutation attack)  
3               0  (Det. solv. fix. <o,h>, Degenerate, Permutatio...  
4               0                   (Degenerate, Permutation attack)  
7               0                   (Degenerate, Permutation attack)  
17              0                                      (Degenerate,)  
19              0                                      (Degenerate,)  
25              0                                      (Degenerate,)  
27              0                                      (Degenerate,)  
48              0                   (Degenerate, Permutation attack)  
49              0                                      (Degenerate,)  
51              0                   (Degenerate, Permutation attack)  
52              0                   (Degenerate, Permutation attack)  
55              0  (Det. solv. fix. <o,h>, Degenerate, Permutatio...  
57              0                                      (Degenerate,)  
59              0                   (Degenerate, Permutation attack)

a  b  c  d  e  f   j     i brs_attack pgv_attack linicrypt_attack  \
2   0  0  1  1  0  1   3  13.0          c          B              TBD   
14  1  1  1  1  0  1  15  14.0          c          B              TBD   
16  0  0  0  1  1  0  17  15.0          c          B              TBD   
18  0  0  1  1  1  0  19  16.0          c          B              TBD   
20  0  1  0  1  1  0  21  17.0          c          B              TBD   
30  1  1  1  1  1  0  31  18.0          c          B              TBD   
32  0  0  0  1  1  1  33  19.0          c          B              TBD   
36  0  1  0  1  1  1  37  20.0          c          B              TBD   

    linicrypt_num linicrypt_all_attacks  
2               4                    ()  
14              4                    ()  
16              4                    ()  
18              4                    ()  
20              4                    ()  
30              4                    ()  
32              4                    ()  
36              4                    ()

a  b  c  d  e  f   j   i brs_attack pgv_attack linicrypt_attack  \
38  0  1  1  1  1  1  39 NaN          g          B              TBD   
39  0  1  0  0  1  1  40 NaN          g          B              TBD   
42  1  0  1  1  1  1  43 NaN          g          B              TBD   
54  0  1  1  1  0  0  55 NaN          g          B              TBD   
58  1  0  1  1  0  0  59 NaN          g          B              TBD   

    linicrypt_num linicrypt_all_attacks  
38              4                    ()  
39              4                    ()  
42              4                    ()  
54              4                    ()  
58              4                    ()

a  b  c  d  e  f   j   i brs_attack pgv_attack  \
1   0  0  1  0  0  1   2 NaN          b          D   
9   1  0  1  0  0  1  10 NaN          b          D   
11  1  0  0  0  0  1  12 NaN          b          D   
21  0  1  1  0  1  0  22 NaN          b          D   
23  0  1  0  0  1  0  24 NaN          b          D   
29  1  1  1  0  1  0  30 NaN          b          D   
31  1  1  0  0  1  0  32 NaN          b          D   
33  0  0  1  0  1  1  34 NaN          b          D   
41  1  0  1  0  1  1  42 NaN          b          D   
43  1  0  0  0  1  1  44 NaN          b          D   
53  0  1  1  0  0  0  54 NaN          b          D   
61  1  1  1  0  0  0  62 NaN          b          D   

                     linicrypt_attack  linicrypt_num  \
1   $\<\O, \vh\>$-Collision Structure              1   
9   $\<\O, \vh\>$-Collision Structure              1   
11  $\<\O, \vh\>$-Collision Structure              1   
21  $\<\O, \vh\>$-Collision Structure              1   
23  $\<\O, \vh\>$-Collision Structure              1   
29  $\<\O, \vh\>$-Collision Structure              1   
31  $\<\O, \vh\>$-Collision Structure              1   
33  $\<\O, \vh\>$-Collision Structure              1   
41  $\<\O, \vh\>$-Collision Structure              1   
43  $\<\O, \vh\>$-Collision Structure              1   
53  $\<\O, \vh\>$-Collision Structure              1   
61  $\<\O, \vh\>$-Collision Structure              1   

                          linicrypt_all_attacks  
1                      (Det. solv. fix. <o,h>,)  
9                      (Det. solv. fix. <o,h>,)  
11  (Det. solv. fix. <o,h>, Permutation attack)  
21                     (Det. solv. fix. <o,h>,)  
23                     (Det. solv. fix. <o,h>,)  
29                     (Det. solv. fix. <o,h>,)  
31                     (Det. solv. fix. <o,h>,)  
33                     (Det. solv. fix. <o,h>,)  
41                     (Det. solv. fix. <o,h>,)  
43                     (Det. solv. fix. <o,h>,)  
53                     (Det. solv. fix. <o,h>,)  
61                     (Det. solv. fix. <o,h>,)

a  b  c  d  e  f   j   i brs_attack pgv_attack linicrypt_attack  \
35  0  0  0  0  1  1  36 NaN          b          D       Degenerate   
63  1  1  0  0  0  0  64 NaN          b          D       Degenerate   

    linicrypt_num                              linicrypt_all_attacks  
35              0                (Det. solv. fix. <o,h>, Degenerate)  
63              0  (Det. solv. fix. <o,h>, Degenerate, Permutatio...

a  b  c  d  e  f   j   i brs_attack pgv_attack linicrypt_attack  \
34  0  0  1  1  1  1  35 NaN          g          F       Degenerate   
46  1  1  1  1  1  1  47 NaN          g          F       Degenerate   
47  1  1  0  0  1  1  48 NaN          g          F       Degenerate   
50  0  0  1  1  0  0  51 NaN          g          F       Degenerate   
62  1  1  1  1  0  0  63 NaN          g          F       Degenerate   

    linicrypt_num linicrypt_all_attacks  
34              0         (Degenerate,)  
46              0         (Degenerate,)  
47              0         (Degenerate,)  
50              0         (Degenerate,)  
62              0         (Degenerate,)

a  b  c  d  e  f   j     i brs_attack pgv_attack linicrypt_attack  \
6   0  1  1  1  0  1   7   9.0          e         FP           Secure   
10  1  0  1  1  0  1  11  11.0          e         FP           Secure   
22  0  1  1  1  1  0  23  12.0          e         FP           Secure   
24  1  0  0  1  1  0  25   5.0          e         FP           Secure   
26  1  0  1  1  1  0  27  10.0          e         FP           Secure   
28  1  1  0  1  1  0  29   7.0          e         FP           Secure   
40  1  0  0  1  1  1  41   8.0          e         FP           Secure   
44  1  1  0  1  1  1  45   6.0          e         FP           Secure   

    linicrypt_num     linicrypt_all_attacks  
6               3  (Secure by MD Paradigm,)  
10              3  (Secure by MD Paradigm,)  
22              3  (Secure by MD Paradigm,)  
24              3  (Secure by MD Paradigm,)  
26              3  (Secure by MD Paradigm,)  
28              3  (Secure by MD Paradigm,)  
40              3  (Secure by MD Paradigm,)  
44              3  (Secure by MD Paradigm,)

a  b  c  d  e  f   j   i brs_attack pgv_attack    linicrypt_attack  \
8   1  0  0  1  0  1   9 NaN          f          P  Permutation attack   
12  1  1  0  1  0  1  13 NaN          f          P  Permutation attack   
15  1  1  0  0  0  1  16 NaN          f          P  Permutation attack   
56  1  0  0  1  0  0  57 NaN          f          P  Permutation attack   
60  1  1  0  1  0  0  61 NaN          f          P  Permutation attack   

    linicrypt_num  linicrypt_all_attacks  
8               2  (Permutation attack,)  
12              2  (Permutation attack,)  
15              2  (Permutation attack,)  
56              2  (Permutation attack,)  
60              2  (Permutation attack,)

In [7]:
from itertools import permutations
from copy import copy

def is_in_span(Q: list[np.array], F:list[np.array]):
    #print(f"Q: {Q}")
    #print(f"F: {F}")
    #print("rank F:", matrix_rank(F))
    #print("rank Q + F: ", matrix_rank(Q + F))
    return matrix_rank(Q + F) == matrix_rank(F)

def unsolv_with_ordering_fixing(ordering, Fix):
    #print("Ordering: ", ordering)
    #print()
    #print("Fix:", Fix)
    #print()
    Fix = [f.reshape(-1) for f in Fix]
    for (k,x,y) in ordering:
        k = k.reshape(-1)
        x = x.reshape(-1)
        y = y.reshape(-1)
        #print("k,x,y: ", k,x,y)
        if is_in_span([y], Fix + [k,x]) and is_in_span([x], Fix + [k,y]):
            return True
        Fix += [k,x,y]
        
def solv_fix(C: list[(np.array, np.array, np.array)], Fix: list[np.array]):
    return any(not unsolv_with_ordering_fixing(ordering, Fix) for ordering in permutations(C))

def in_span(x: list[np.array], F: list[np.array]):
    F_dim = matrix_rank(np.concatenate(F))
    x_F_dim = matrix_rank(np.concatenate(x + F))
    #print("x: ", x)
    #print("F: ", F)
    #print(F_dim, x_F_dim)
    return F_dim == x_F_dim

def dim(F: list[np.array]):
    return matrix_rank(np.concatenate(F))

def constraint_det_solvable_fixing(c, Fix):
    k,x,y = c
    forward = in_span([k,x], Fix) and not in_span([y], Fix)
    backward = in_span([k,x], Fix) and not in_span([y], Fix)
    return forward or backward

def is_solution_ordering_fixing(ordering, Fix):
    return all(constraint_det_solvable_fixing(c, rowsp(C[:i]) + F) for i, c in enumerate(C))
        

def det_solv_fixing(C: list[(np.array, np.array, np.array)], Fix: list[np.array]):
    # np.arrays have shape (-1,base)
    return any(is_solution_ordering_fixing(ordering, Fix) for ordering in permutations(C))

def constraint_solv_fixing(c, Fix):
    k,x,y = c
    #print("c: ", c)
    #print("Fix: ", Fix)
    forward = not in_span([y], Fix + [k,x])
    backward = not in_span([x], Fix + [k,y])
    #print(forward, backward)
    return forward or backward

def constraint_non_det_solv_fixing(c, Fix):
    k,x,y = c
    forward = not in_span([y], Fix + [k,x]) and dim(Fix + [k,x]) > dim(Fix)
    backward = not in_span([x], Fix + [k,y]) and dim(Fix + [k,y]) > dim(Fix)
    return forward or backward

def non_det_solution_ordering_fixing(ordering, F):
    #print("Ccs: ", ordering)
    #print("Fixing: ", F)
    if len(ordering) == 0:
        return dim(F) < F[0].shape[1]
    solv = all(constraint_solv_fixing(c, rowsp(ordering[:i]) + F) for i, c in enumerate(ordering))
    #print("solv: ", solv)
    non_det = any(constraint_non_det_solv_fixing(c, rowsp(ordering[:i]) + F) for i, c in enumerate(ordering))
    #print("non_det: ", non_det)
    return solv and non_det


def rowsp(C):
    return sum([[k,x,y] for k,x,y in C], start=[])

def has_collision_structure(O, C):
    for ordering in permutations(C):
        #print("Ordering of C: ", ordering)
        for i in range(len(ordering) + 1):
            Cfix = ordering[:i]
            Ccs = ordering[i:]
            Fix = rowsp(Cfix) + [O]
            if non_det_solution_ordering_fixing(Ccs, Fix):
                #print("wtf")
                return True
    return False

def alg_rep_MD(f_O, c: (np.array, np.array, np.array), n):
    MD_C = []
    base = n + 1 + n
    f_k,f_x,f_y = c
    
    # base variables
    def y(i):
        return np.eye(1,base,n+i, dtype=int)
    
    def m(i):
        return np.eye(1,base,i-1, dtype=int)
    
    # intermediate variables
    def h(i):
        if i == -1:
            return np.eye(1,base,-1, dtype=int)
        return f_O @ np.concatenate([h(i-1), m(i), y(i)])
    
    def k(i):
        return f_k @ np.concatenate([h(i-1), m(i), y(i)])
        
    def x(i):
        return f_x @ np.concatenate([h(i-1), m(i), y(i)])
    
    MD_C = [(k(i), x(i), y(i)) for i in range(0, n+1)]
    O = h(n)
    
    #print(m(1))
    #print(y(0))
    #print(y(1))
    
    return (O, MD_C)


o = np.array([[0,1,1]])
k = np.array([[1,1,0]])
x = np.array([[0,1,0]])
y = np.array([[0,0,1]])
c = (k,x,y)
O, C = alg_rep_MD(o, c, 1)
print(f"O = {O}")
print(f"C = {C}")

O = [[1 0 1]]
C = [(array([[0, 0, 0]]), array([[0, 0, 0]]), array([[0, 1, 0]])), (array([[1, 1, 0]]), array([[1, 0, 0]]), array([[0, 0, 1]]))]


In [8]:
has_collision_structure(O, C)

False

In [9]:
def row_to_O_C(row):
    a,b,c,d,e,f = row.a,row.b,row.c,row.d,row.e,row.f
    O = np.array([[a,b,1]])
    k = np.array([[c,d,0]])
    x = np.array([[e,f,0]])
    y = np.array([[0,0,1]])
    return O, (k,x,y)

def row_to_MD_solvable(n, row):
    f_O, f_c = row_to_O_C(row)
    O, C = alg_rep_MD(f_O, f_c, n)
    return has_collision_structure(O, C)


df["Linicrypt MD1 CS"] = df.apply(lambda row: row_to_MD_solvable(1, row), axis=1)
df["Linicrypt MD2 CS"] = df.apply(lambda row: row_to_MD_solvable(2, row), axis=1)
df["Linicrypt MD3 CS"] = df.apply(lambda row: row_to_MD_solvable(3, row), axis=1)

In [10]:
for brs_attack, group in df.sort_values(["a","b"]).groupby(["linicrypt_attack"]):
    display(group)

a  b  c  d  e  f   j   i brs_attack pgv_attack  \
1   0  0  1  0  0  1   2 NaN          b          D   
33  0  0  1  0  1  1  34 NaN          b          D   
21  0  1  1  0  1  0  22 NaN          b          D   
23  0  1  0  0  1  0  24 NaN          b          D   
53  0  1  1  0  0  0  54 NaN          b          D   
9   1  0  1  0  0  1  10 NaN          b          D   
11  1  0  0  0  0  1  12 NaN          b          D   
41  1  0  1  0  1  1  42 NaN          b          D   
43  1  0  0  0  1  1  44 NaN          b          D   
29  1  1  1  0  1  0  30 NaN          b          D   
31  1  1  0  0  1  0  32 NaN          b          D   
61  1  1  1  0  0  0  62 NaN          b          D   

                     linicrypt_attack  linicrypt_num  \
1   $\<\O, \vh\>$-Collision Structure              1   
33  $\<\O, \vh\>$-Collision Structure              1   
21  $\<\O, \vh\>$-Collision Structure              1   
23  $\<\O, \vh\>$-Collision Structure              1   
53  $\<\O, \vh\>$-Collision Structure              1   
9   $\<\O, \vh\>$-Collision Structure              1   
11  $\<\O, \vh\>$-Collision Structure              1   
41  $\<\O, \vh\>$-Collision Structure              1   
43  $\<\O, \vh\>$-Collision Structure              1   
29  $\<\O, \vh\>$-Collision Structure              1   
31  $\<\O, \vh\>$-Collision Structure              1   
61  $\<\O, \vh\>$-Collision Structure              1   

                          linicrypt_all_attacks  Linicrypt MD1 CS  \
1                      (Det. solv. fix. <o,h>,)             False   
33                     (Det. solv. fix. <o,h>,)             False   
21                     (Det. solv. fix. <o,h>,)             False   
23                     (Det. solv. fix. <o,h>,)             False   
53                     (Det. solv. fix. <o,h>,)             False   
9                      (Det. solv. fix. <o,h>,)             False   
11  (Det. solv. fix. <o,h>, Permutation attack)             False   
41                     (Det. solv. fix. <o,h>,)             False   
43                     (Det. solv. fix. <o,h>,)             False   
29                     (Det. solv. fix. <o,h>,)             False   
31                     (Det. solv. fix. <o,h>,)             False   
61                     (Det. solv. fix. <o,h>,)             False   

    Linicrypt MD2 CS  Linicrypt MD3 CS  
1               True              True  
33              True              True  
21              True              True  
23              True              True  
53              True              True  
9               True              True  
11              True              True  
41              True              True  
43              True              True  
29              True              True  
31              True              True  
61              True              True

a  b  c  d  e  f   j   i brs_attack pgv_attack linicrypt_attack  \
0   0  0  0  1  0  1   1 NaN          a          -       Degenerate   
3   0  0  0  0  0  1   4 NaN          a          -       Degenerate   
17  0  0  1  0  1  0  18 NaN          a          -       Degenerate   
19  0  0  0  0  1  0  20 NaN          a          -       Degenerate   
34  0  0  1  1  1  1  35 NaN          g          F       Degenerate   
35  0  0  0  0  1  1  36 NaN          b          D       Degenerate   
48  0  0  0  1  0  0  49 NaN          a          -       Degenerate   
49  0  0  1  0  0  0  50 NaN          a          -       Degenerate   
50  0  0  1  1  0  0  51 NaN          g          F       Degenerate   
51  0  0  0  0  0  0  52 NaN          a          -       Degenerate   
4   0  1  0  1  0  1   5 NaN          a          -       Degenerate   
7   0  1  0  0  0  1   8 NaN          a          -       Degenerate   
52  0  1  0  1  0  0  53 NaN          a          -       Degenerate   
55  0  1  0  0  0  0  56 NaN          a          -       Degenerate   
25  1  0  1  0  1  0  26 NaN          a          -       Degenerate   
27  1  0  0  0  1  0  28 NaN          a          -       Degenerate   
57  1  0  1  0  0  0  58 NaN          a          -       Degenerate   
59  1  0  0  0  0  0  60 NaN          a          -       Degenerate   
46  1  1  1  1  1  1  47 NaN          g          F       Degenerate   
47  1  1  0  0  1  1  48 NaN          g          F       Degenerate   
62  1  1  1  1  0  0  63 NaN          g          F       Degenerate   
63  1  1  0  0  0  0  64 NaN          b          D       Degenerate   

    linicrypt_num                              linicrypt_all_attacks  \
0               0                   (Degenerate, Permutation attack)   
3               0  (Det. solv. fix. <o,h>, Degenerate, Permutatio...   
17              0                                      (Degenerate,)   
19              0                                      (Degenerate,)   
34              0                                      (Degenerate,)   
35              0                (Det. solv. fix. <o,h>, Degenerate)   
48              0                   (Degenerate, Permutation attack)   
49              0                                      (Degenerate,)   
50              0                                      (Degenerate,)   
51              0                   (Degenerate, Permutation attack)   
4               0                   (Degenerate, Permutation attack)   
7               0                   (Degenerate, Permutation attack)   
52              0                   (Degenerate, Permutation attack)   
55              0  (Det. solv. fix. <o,h>, Degenerate, Permutatio...   
25              0                                      (Degenerate,)   
27              0                                      (Degenerate,)   
57              0                                      (Degenerate,)   
59              0                   (Degenerate, Permutation attack)   
46              0                                      (Degenerate,)   
47              0                                      (Degenerate,)   
62              0                                      (Degenerate,)   
63              0  (Det. solv. fix. <o,h>, Degenerate, Permutatio...   

    Linicrypt MD1 CS  Linicrypt MD2 CS  Linicrypt MD3 CS  
0              False              True              True  
3              False              True              True  
17              True              True              True  
19              True              True              True  
34             False              True              True  
35             False              True              True  
48             False              True              True  
49              True              True              True  
50             False              True              True  
51              True              True              True  
4              False              True              True  
7    

a  b  c  d  e  f   j   i brs_attack pgv_attack    linicrypt_attack  \
8   1  0  0  1  0  1   9 NaN          f          P  Permutation attack   
56  1  0  0  1  0  0  57 NaN          f          P  Permutation attack   
12  1  1  0  1  0  1  13 NaN          f          P  Permutation attack   
15  1  1  0  0  0  1  16 NaN          f          P  Permutation attack   
60  1  1  0  1  0  0  61 NaN          f          P  Permutation attack   

    linicrypt_num  linicrypt_all_attacks  Linicrypt MD1 CS  Linicrypt MD2 CS  \
8               2  (Permutation attack,)             False             False   
56              2  (Permutation attack,)             False             False   
12              2  (Permutation attack,)             False             False   
15              2  (Permutation attack,)             False             False   
60              2  (Permutation attack,)             False             False   

    Linicrypt MD3 CS  
8              False  
56             False  
12             False  
15             False  
60             False

a  b  c  d  e  f   j     i brs_attack    pgv_attack linicrypt_attack  \
5   0  1  1  0  0  1   6   1.0          d  $\checkmark$           Secure   
6   0  1  1  1  0  1   7   9.0          e            FP           Secure   
22  0  1  1  1  1  0  23  12.0          e            FP           Secure   
37  0  1  1  0  1  1  38   4.0          d  $\checkmark$           Secure   
10  1  0  1  1  0  1  11  11.0          e            FP           Secure   
24  1  0  0  1  1  0  25   5.0          e            FP           Secure   
26  1  0  1  1  1  0  27  10.0          e            FP           Secure   
40  1  0  0  1  1  1  41   8.0          e            FP           Secure   
13  1  1  1  0  0  1  14   3.0          d  $\checkmark$           Secure   
28  1  1  0  1  1  0  29   7.0          e            FP           Secure   
44  1  1  0  1  1  1  45   6.0          e            FP           Secure   
45  1  1  1  0  1  1  46   2.0          d  $\checkmark$           Secure   

    linicrypt_num     linicrypt_all_attacks  Linicrypt MD1 CS  \
5               3  (Secure by MD Paradigm,)             False   
6               3  (Secure by MD Paradigm,)             False   
22              3  (Secure by MD Paradigm,)             False   
37              3  (Secure by MD Paradigm,)             False   
10              3  (Secure by MD Paradigm,)             False   
24              3  (Secure by MD Paradigm,)             False   
26              3  (Secure by MD Paradigm,)             False   
40              3  (Secure by MD Paradigm,)             False   
13              3  (Secure by MD Paradigm,)             False   
28              3  (Secure by MD Paradigm,)             False   
44              3  (Secure by MD Paradigm,)             False   
45              3  (Secure by MD Paradigm,)             False   

    Linicrypt MD2 CS  Linicrypt MD3 CS  
5              False             False  
6              False             False  
22             False             False  
37             False             False  
10             False             False  
24             False             False  
26             False             False  
40             False             False  
13             False             False  
28             False             False  
44             False             False  
45             False             False

a  b  c  d  e  f   j     i brs_attack pgv_attack linicrypt_attack  \
2   0  0  1  1  0  1   3  13.0          c          B              TBD   
16  0  0  0  1  1  0  17  15.0          c          B              TBD   
18  0  0  1  1  1  0  19  16.0          c          B              TBD   
32  0  0  0  1  1  1  33  19.0          c          B              TBD   
20  0  1  0  1  1  0  21  17.0          c          B              TBD   
36  0  1  0  1  1  1  37  20.0          c          B              TBD   
38  0  1  1  1  1  1  39   NaN          g          B              TBD   
39  0  1  0  0  1  1  40   NaN          g          B              TBD   
54  0  1  1  1  0  0  55   NaN          g          B              TBD   
42  1  0  1  1  1  1  43   NaN          g          B              TBD   
58  1  0  1  1  0  0  59   NaN          g          B              TBD   
14  1  1  1  1  0  1  15  14.0          c          B              TBD   
30  1  1  1  1  1  0  31  18.0          c          B              TBD   

    linicrypt_num linicrypt_all_attacks  Linicrypt MD1 CS  Linicrypt MD2 CS  \
2               4                    ()             False             False   
16              4                    ()             False             False   
18              4                    ()             False             False   
32              4                    ()             False             False   
20              4                    ()             False             False   
36              4                    ()             False             False   
38              4                    ()             False             False   
39              4                    ()             False             False   
54              4                    ()             False             False   
42              4                    ()             False             False   
58              4                    ()             False             False   
14              4                    ()             False             False   
30              4                    ()             False             False   

    Linicrypt MD3 CS  
2              False  
16             False  
18             False  
32             False  
20             False  
36             False  
38             False  
39             False  
54             False  
42             False  
58             False  
14             False  
30             False

In [11]:
latex_df = df.copy()
latex_df = latex_df.drop(["Linicrypt MD1 CS", "Linicrypt MD2 CS", "Linicrypt MD3 CS", "linicrypt_all_attacks"], axis=1)
#latex_df[["$a$","$b$","$c$","$d$","$e$","$f$","$j$","$i$"]] = latex_df[["a","b","c","d","e","f","j","i"]]

def rename_math(col):
    if len(col) == 1:
        return f"${col}$"
    return col

latex_df["i"] = latex_df["i"].map(lambda i: str(int(i)) if i == i else "")

rename_attacks = {
    "linicrypt_attack": "Linicrypt Attack",
    "brs_attack": "BRS",
    "pgv_attack": "PGV",
}

latex_df = latex_df.rename(rename_math, axis=1).rename(rename_attacks, axis=1)
latex_df = latex_df.sort_values(["BRS", "PGV"]).set_index(["BRS", "PGV"])
latex_df

$a$  $b$  $c$  $d$  $e$  $f$  $j$ $i$  \
BRS PGV                                                   
a   -               0    0    0    1    0    1    1       
    -               0    0    0    0    0    1    4       
    -               0    1    0    1    0    1    5       
    -               0    1    0    0    0    1    8       
    -               0    0    1    0    1    0   18       
    -               0    0    0    0    1    0   20       
    -               1    0    1    0    1    0   26       
    -               1    0    0    0    1    0   28       
    -               0    0    0    1    0    0   49       
    -               0    0    1    0    0    0   50       
    -               0    0    0    0    0    0   52       
    -               0    1    0    1    0    0   53       
    -               0    1    0    0    0    0   56       
    -               1    0    1    0    0    0   58       
    -               1    0    0    0    0    0   60       
b   D               0    0    1    0    0    1    2       
    D               1    0    1    0    0    1   10       
    D               1    0    0    0    0    1   12       
    D               0    1    1    0    1    0   22       
    D               0    1    0    0    1    0   24       
    D               1    1    1    0    1    0   30       
    D               1    1    0    0    1    0   32       
    D               0    0    1    0    1    1   34       
    D               0    0    0    0    1    1   36       
    D               1    0    1    0    1    1   42       
    D               1    0    0    0    1    1   44       
    D               0    1    1    0    0    0   54       
    D               1    1    1    0    0    0   62       
    D               1    1    0    0    0    0   64       
c   B               0    0    1    1    0    1    3  13   
    B               1    1    1    1    0    1   15  14   
    B               0    0    0    1    1    0   17  15   
    B               0    0    1    1    1    0   19  16   
    B               0    1    0    1    1    0   21  17   
    B               1    1    1    1    1    0   31  18   
    B               0    0    0    1    1    1   33  19   
    B               0    1    0    1    1    1   37  20   
d   $\checkmark$    0    1    1    0    0    1    6   1   
    $\checkmark$    1    1    1    0    0    1   14   3   
    $\checkmark$    0    1    1    0    1    1   38   4   
    $\checkmark$    1    1    1    0    1    1   46   2   
e   FP              0    1    1    1    0    1    7   9   
    FP              1    0    1    1    0    1   11  11   
    FP              0    1    1    1    1    0   23  12   
    FP              1    0    0    1    1    0   25   5   
    FP              1    0    1    1    1    0   27  10   
    FP              1    1    0    1    1    0   29   7   
    FP              1    0    0    1    1    1   41   8   
    FP              1    1    0    1    1    1   45   6   
f   P               1    0    0    1    0    1    9       
    P               1    1    0    1    0    1   13       
    P               1    1    0    0    0    1   16       
    P               1    0    0    1    0    0   57       
    P               1    1    0    1    0    0   61       
g   B               0    1    1    1    1    1   39       
    B               0    1    0    0    1    1   40       
    B               1    0    1    1    1    1   43       
    B               0    1    1    1    0    0   55       
    B               1    0    1    1    0    0   59       
    F               0    0    1    1    1    1   35       
    F               1    1    1    1    1    1   47       
    F               1    1    0    0    1    1   48       
    F               0    0    1    1    0    0   51       
    F               1    1    1    1    0    0   63       

                                   Linicrypt Attack  linicrypt_num  
BRS PGV                                               

In [27]:
def second_pi(row):
    linicrypt_attack = row[0]
    print(row)
    if linicrypt_attack == "Secure":
        return "$\leq N/|\F|$"
    elif linicrypt_attack == "Degenerate" or "Collision" in linicrypt_attack:
        return "1"
    elif linicrypt_attack == "Permutation attack":
        return "1"
    else:
        return "-"

df["\#"] = 1
df = df.sort_values("linicrypt_num")
display(df)
summary_df = df[["linicrypt_attack", "brs_attack", "pgv_attack", "\#", "linicrypt_num"]].groupby(["linicrypt_num", "linicrypt_attack", "brs_attack", "pgv_attack"]).count()
summary_df.index = summary_df.index.rename(rename_attacks)
summary_df.index = summary_df.index.droplevel(0)
summary_df["$\spr(\A, \H^n_f)$"] = summary_df.index.map(second_pi)
display(summary_df)

a  b  c  d  e  f   j     i brs_attack    pgv_attack  \
0   0  0  0  1  0  1   1   NaN          a             -   
35  0  0  0  0  1  1  36   NaN          b             D   
46  1  1  1  1  1  1  47   NaN          g             F   
47  1  1  0  0  1  1  48   NaN          g             F   
25  1  0  1  0  1  0  26   NaN          a             -   
48  0  0  0  1  0  0  49   NaN          a             -   
52  0  1  0  1  0  0  53   NaN          a             -   
4   0  1  0  1  0  1   5   NaN          a             -   
3   0  0  0  0  0  1   4   NaN          a             -   
55  0  1  0  0  0  0  56   NaN          a             -   
34  0  0  1  1  1  1  35   NaN          g             F   
7   0  1  0  0  0  1   8   NaN          a             -   
50  0  0  1  1  0  0  51   NaN          g             F   
62  1  1  1  1  0  0  63   NaN          g             F   
27  1  0  0  0  1  0  28   NaN          a             -   
51  0  0  0  0  0  0  52   NaN          a             -   
57  1  0  1  0  0  0  58   NaN          a             -   
59  1  0  0  0  0  0  60   NaN          a             -   
49  0  0  1  0  0  0  50   NaN          a             -   
19  0  0  0  0  1  0  20   NaN          a             -   
63  1  1  0  0  0  0  64   NaN          b             D   
17  0  0  1  0  1  0  18   NaN          a             -   
23  0  1  0  0  1  0  24   NaN          b             D   
53  0  1  1  0  0  0  54   NaN          b             D   
61  1  1  1  0  0  0  62   NaN          b             D   
1   0  0  1  0  0  1   2   NaN          b             D   
43  1  0  0  0  1  1  44   NaN          b             D   
21  0  1  1  0  1  0  22   NaN          b             D   
33  0  0  1  0  1  1  34   NaN          b             D   
11  1  0  0  0  0  1  12   NaN          b             D   
9   1  0  1  0  0  1  10   NaN          b             D   
41  1  0  1  0  1  1  42   NaN          b             D   
31  1  1  0  0  1  0  32   NaN          b             D   
29  1  1  1  0  1  0  30   NaN          b             D   
15  1  1  0  0  0  1  16   NaN          f             P   
56  1  0  0  1  0  0  57   NaN          f             P   
12  1  1  0  1  0  1  13   NaN          f             P   
8   1  0  0  1  0  1   9   NaN          f             P   
60  1  1  0  1  0  0  61   NaN          f             P   
26  1  0  1  1  1  0  27  10.0          e            FP   
24  1  0  0  1  1  0  25   5.0          e            FP   
28  1  1  0  1  1  0  29   7.0          e            FP   
13  1  1  1  0  0  1  14   3.0          d  $\checkmark$   
22  0  1  1  1  1  0  23  12.0          e            FP   
37  0  1  1  0  1  1  38   4.0          d  $\checkmark$   
5   0  1  1  0  0  1   6   1.0          d  $\checkmark$   
45  1  1  1  0  1  1  46   2.0          d  $\checkmark$   
10  1  0  1  1  0  1  11  11.0          e            FP   
6   0  1  1  1  0  1   7   9.0          e            FP   
44  1  1  0  1  1  1  45   6.0          e            FP   
40  1  0  0  1  1  1  41   8.0          e            FP   
54  0  1  1  1  0  0  55   NaN          g             B   
38  0  1  1  1  1  1  39   NaN          g             B   
36  0  1  0  1  1  1  37  20.0          c             B   
32  0  0  0  1  1  1  33  19.0          c             B   
14  1  1  1  1  0  1  15  14.0          c             B   
20  0  1  0  1  1  0  21  17.0          c             B   
2   0  0  1  1  0  1   3  13.0          c             B   
16  0  0  0  1  1  0  17  15.0          c             B   
39  0  1  0  0  1  1  40   NaN          g             B   
42  1  0  1  1  1  1  43   NaN          g             B   
58  1  0  1  1  0  0  59   NaN          g             B   
30  1  1  1  1  1  0  31  18.0          c             B   
18  0  0  1  1  1  0  19  16.0          c             B   

                     linicrypt_attack  linicrypt_num  \
0                          Degenerate              0   
35                         Degenerate              0   


('Degenerate', 'a', '-')
('Degenerate', 'b', 'D')
('Degenerate', 'g', 'F')
('$\\<\\O, \\vh\\>$-Collision Structure', 'b', 'D')
('Permutation attack', 'f', 'P')
('Secure', 'd', '$\\checkmark$')
('Secure', 'e', 'FP')
('TBD', 'c', 'B')
('TBD', 'g', 'B')


\# $\spr(\A, \H^n_f)$
Linicrypt Attack                  BRS PGV                                
Degenerate                        a   -             15                  1
                                  b   D              2                  1
                                  g   F              5                  1
$\<\O, \vh\>$-Collision Structure b   D             12                  1
Permutation attack                f   P              5                  1
Secure                            d   $\checkmark$   4      $\leq N/|\F|$
                                  e   FP             8      $\leq N/|\F|$
TBD                               c   B              8                  -
                                  g   B              5                  -

In [30]:
with open("../chapters/attacks_summary.tex", "w") as texfile:
    texfile.write(summary_df.style.to_latex(column_format="lllrc", hrules=True,clines="all;data",multirow_align="c"))